#!/usr/bin/with-contenv bash

# load PKCS#12 certificate into unifi controller keystore
# to convert a letsencrypt certificate use the following example
# openssl pkcs12 -export -inkey /etc/letsencrypt/live/mysubdomain.mydomain.com/privkey.pem \ 
#   -in /etc/letsencrypt/live/mysubdomain.mydomain.com/fullchain.pem \
#   -out /config/cert/unifi.p12 -name ubnt -password pass:temppass
[[ -f /config/cert/unifi.p12 ]] && \
    keytool -importkeystore -deststorepass aircontrolenterprise -destkeypass aircontrolenterprise -destkeystore /config/data/keystore \
        -srckeystore /config/cert/unifi.p12 -srcstoretype PKCS12 -srcstorepass temppass -alias ubnt -noprompt
    

# generate key if none are available
[[ ! -f /config/data/keystore ]] && \
  keytool -genkey -keyalg RSA -alias unifi -keystore /config/data/keystore \
    -storepass aircontrolenterprise -keypass aircontrolenterprise -validity 1825 \
    -keysize 4096 -dname "cn=unifi"

# permissions
chown mcf:mcf \
	/config/data/keystore
